[2024-10-10T00:39:26.681+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: train_ml_model_dag.train_model manual__2024-10-10T00:34:21.847464+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-10-10T00:58:06.627+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: train_ml_model_dag.train_model manual__2024-10-10T00:34:21.847464+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
