[2024-10-11T22:02:09.411+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-11T22:02:09.431+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_ml_model_dag.train_model manual__2024-10-11T22:02:05.826759+00:00 [queued]>
[2024-10-11T22:02:09.439+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_ml_model_dag.train_model manual__2024-10-11T22:02:05.826759+00:00 [queued]>
[2024-10-11T22:02:09.440+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-11T22:02:09.448+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_model> on 2024-10-11 22:02:05.826759+00:00
[2024-10-11T22:02:09.458+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=52) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-11T22:02:09.460+0000] {standard_task_runner.py:63} INFO - Started process 54 to run task
[2024-10-11T22:02:09.461+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'train_ml_model_dag', 'train_model', 'manual__2024-10-11T22:02:05.826759+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/train_ml_model.py', '--cfg-path', '/tmp/tmp_ncbg7jo']
[2024-10-11T22:02:09.464+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask train_model
[2024-10-11T22:02:09.527+0000] {task_command.py:426} INFO - Running <TaskInstance: train_ml_model_dag.train_model manual__2024-10-11T22:02:05.826759+00:00 [running]> on host 8a428b66f6b4
[2024-10-11T22:02:09.617+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Michael Mora' AIRFLOW_CTX_DAG_ID='train_ml_model_dag' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-11T22:02:05.826759+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-11T22:02:05.826759+00:00'
[2024-10-11T22:02:09.619+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-11T22:02:09.621+0000] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venveth_bj44 --system-site-packages --python=python
[2024-10-11T22:02:09.623+0000] {process_utils.py:187} INFO - Output:
[2024-10-11T22:02:10.751+0000] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 572ms
[2024-10-11T22:02:10.756+0000] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venveth_bj44, clear=False, no_vcs_ignore=False, global=True)
[2024-10-11T22:02:10.757+0000] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-10-11T22:02:10.760+0000] {process_utils.py:191} INFO -     added seed packages: pip==24.0
[2024-10-11T22:02:10.761+0000] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-10-11T22:02:10.782+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venveth_bj44/bin/pip install -r /tmp/venveth_bj44/requirements.txt
[2024-10-11T22:02:10.791+0000] {process_utils.py:187} INFO - Output:
[2024-10-11T22:02:13.578+0000] {process_utils.py:191} INFO - 
[2024-10-11T22:02:13.582+0000] {process_utils.py:191} INFO - [notice] A new release of pip is available: 24.0 -> 24.2
[2024-10-11T22:02:13.584+0000] {process_utils.py:191} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-10-11T22:02:13.667+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venveth_bj44/bin/python /tmp/venv-callb66gkybv/script.py /tmp/venv-callb66gkybv/script.in /tmp/venv-callb66gkybv/script.out /tmp/venv-callb66gkybv/string_args.txt /tmp/venv-callb66gkybv/termination.log
[2024-10-11T22:02:13.669+0000] {process_utils.py:187} INFO - Output:
[2024-10-11T22:02:15.343+0000] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-10-11T22:02:15.345+0000] {process_utils.py:191} INFO -   File "/tmp/venv-callb66gkybv/script.py", line 16, in <module>
[2024-10-11T22:02:15.346+0000] {process_utils.py:191} INFO -     @task .virtualenv()
[2024-10-11T22:02:15.347+0000] {process_utils.py:191} INFO -      ^^^^
[2024-10-11T22:02:15.347+0000] {process_utils.py:191} INFO - NameError: name 'task' is not defined
[2024-10-11T22:02:15.544+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-11T22:02:15.546+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 497, in _execute_python_callable_in_subprocess
    execute_in_subprocess(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 172, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 195, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venveth_bj44/bin/python', '/tmp/venv-callb66gkybv/script.py', '/tmp/venv-callb66gkybv/script.in', '/tmp/venv-callb66gkybv/script.out', '/tmp/venv-callb66gkybv/string_args.txt', '/tmp/venv-callb66gkybv/termination.log']' returned non-zero exit status 1.
[2024-10-11T22:02:15.570+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=train_ml_model_dag, task_id=train_model, run_id=manual__2024-10-11T22:02:05.826759+00:00, execution_date=20241011T220205, start_date=20241011T220209, end_date=20241011T220215
[2024-10-11T22:02:15.583+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task train_model (Command '['/tmp/venveth_bj44/bin/python', '/tmp/venv-callb66gkybv/script.py', '/tmp/venv-callb66gkybv/script.in', '/tmp/venv-callb66gkybv/script.out', '/tmp/venv-callb66gkybv/string_args.txt', '/tmp/venv-callb66gkybv/termination.log']' returned non-zero exit status 1.; 54)
[2024-10-11T22:02:15.630+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-11T22:02:15.662+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-11T22:02:15.664+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
