[2024-10-11T22:07:17.163+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-11T22:07:17.181+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_ml_model_dag.train_model manual__2024-10-11T22:02:05.826759+00:00 [queued]>
[2024-10-11T22:07:17.187+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_ml_model_dag.train_model manual__2024-10-11T22:02:05.826759+00:00 [queued]>
[2024-10-11T22:07:17.188+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-10-11T22:07:17.196+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_model> on 2024-10-11 22:02:05.826759+00:00
[2024-10-11T22:07:17.201+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=161) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-11T22:07:17.203+0000] {standard_task_runner.py:63} INFO - Started process 170 to run task
[2024-10-11T22:07:17.204+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'train_ml_model_dag', 'train_model', 'manual__2024-10-11T22:02:05.826759+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/train_ml_model.py', '--cfg-path', '/tmp/tmpd8ds2sbz']
[2024-10-11T22:07:17.207+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask train_model
[2024-10-11T22:07:17.260+0000] {task_command.py:426} INFO - Running <TaskInstance: train_ml_model_dag.train_model manual__2024-10-11T22:02:05.826759+00:00 [running]> on host 8a428b66f6b4
[2024-10-11T22:07:17.361+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Michael Mora' AIRFLOW_CTX_DAG_ID='train_ml_model_dag' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-11T22:02:05.826759+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-11T22:02:05.826759+00:00'
[2024-10-11T22:07:17.368+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-11T22:07:17.370+0000] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venva9luckvx --system-site-packages --python=python
[2024-10-11T22:07:17.372+0000] {process_utils.py:187} INFO - Output:
[2024-10-11T22:07:18.045+0000] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 280ms
[2024-10-11T22:07:18.046+0000] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venva9luckvx, clear=False, no_vcs_ignore=False, global=True)
[2024-10-11T22:07:18.047+0000] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-10-11T22:07:18.048+0000] {process_utils.py:191} INFO -     added seed packages: pip==24.0
[2024-10-11T22:07:18.050+0000] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-10-11T22:07:18.077+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venva9luckvx/bin/pip install -r /tmp/venva9luckvx/requirements.txt
[2024-10-11T22:07:18.079+0000] {process_utils.py:187} INFO - Output:
[2024-10-11T22:07:21.537+0000] {process_utils.py:191} INFO - 
[2024-10-11T22:07:21.539+0000] {process_utils.py:191} INFO - [notice] A new release of pip is available: 24.0 -> 24.2
[2024-10-11T22:07:21.540+0000] {process_utils.py:191} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-10-11T22:07:21.624+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venva9luckvx/bin/python /tmp/venv-call2eynmz7n/script.py /tmp/venv-call2eynmz7n/script.in /tmp/venv-call2eynmz7n/script.out /tmp/venv-call2eynmz7n/string_args.txt /tmp/venv-call2eynmz7n/termination.log
[2024-10-11T22:07:21.626+0000] {process_utils.py:187} INFO - Output:
[2024-10-11T22:07:23.061+0000] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-10-11T22:07:23.063+0000] {process_utils.py:191} INFO -   File "/tmp/venv-call2eynmz7n/script.py", line 16, in <module>
[2024-10-11T22:07:23.064+0000] {process_utils.py:191} INFO -     @task .virtualenv()
[2024-10-11T22:07:23.065+0000] {process_utils.py:191} INFO -      ^^^^
[2024-10-11T22:07:23.065+0000] {process_utils.py:191} INFO - NameError: name 'task' is not defined
[2024-10-11T22:07:23.244+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-11T22:07:23.246+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 497, in _execute_python_callable_in_subprocess
    execute_in_subprocess(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 172, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 195, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venva9luckvx/bin/python', '/tmp/venv-call2eynmz7n/script.py', '/tmp/venv-call2eynmz7n/script.in', '/tmp/venv-call2eynmz7n/script.out', '/tmp/venv-call2eynmz7n/string_args.txt', '/tmp/venv-call2eynmz7n/termination.log']' returned non-zero exit status 1.
[2024-10-11T22:07:23.265+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=train_ml_model_dag, task_id=train_model, run_id=manual__2024-10-11T22:02:05.826759+00:00, execution_date=20241011T220205, start_date=20241011T220717, end_date=20241011T220723
[2024-10-11T22:07:23.278+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 30 for task train_model (Command '['/tmp/venva9luckvx/bin/python', '/tmp/venv-call2eynmz7n/script.py', '/tmp/venv-call2eynmz7n/script.in', '/tmp/venv-call2eynmz7n/script.out', '/tmp/venv-call2eynmz7n/string_args.txt', '/tmp/venv-call2eynmz7n/termination.log']' returned non-zero exit status 1.; 170)
[2024-10-11T22:07:23.326+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-11T22:07:23.343+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-11T22:07:23.344+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
