[2024-10-11T22:08:19.485+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-11T22:08:19.501+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_ml_model_dag.train_model manual__2024-10-11T22:08:17.954348+00:00 [queued]>
[2024-10-11T22:08:19.505+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_ml_model_dag.train_model manual__2024-10-11T22:08:17.954348+00:00 [queued]>
[2024-10-11T22:08:19.506+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-11T22:08:19.512+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_model> on 2024-10-11 22:08:17.954348+00:00
[2024-10-11T22:08:19.519+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=202) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-11T22:08:19.521+0000] {standard_task_runner.py:63} INFO - Started process 204 to run task
[2024-10-11T22:08:19.522+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'train_ml_model_dag', 'train_model', 'manual__2024-10-11T22:08:17.954348+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/train_ml_model.py', '--cfg-path', '/tmp/tmp603nyem5']
[2024-10-11T22:08:19.525+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask train_model
[2024-10-11T22:08:19.570+0000] {task_command.py:426} INFO - Running <TaskInstance: train_ml_model_dag.train_model manual__2024-10-11T22:08:17.954348+00:00 [running]> on host 8a428b66f6b4
[2024-10-11T22:08:19.630+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Michael Mora' AIRFLOW_CTX_DAG_ID='train_ml_model_dag' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-11T22:08:17.954348+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-11T22:08:17.954348+00:00'
[2024-10-11T22:08:19.633+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-11T22:08:19.636+0000] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvfmrxhnl8 --system-site-packages --python=python
[2024-10-11T22:08:19.637+0000] {process_utils.py:187} INFO - Output:
[2024-10-11T22:08:20.129+0000] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 184ms
[2024-10-11T22:08:20.131+0000] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venvfmrxhnl8, clear=False, no_vcs_ignore=False, global=True)
[2024-10-11T22:08:20.132+0000] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-10-11T22:08:20.133+0000] {process_utils.py:191} INFO -     added seed packages: pip==24.0
[2024-10-11T22:08:20.133+0000] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-10-11T22:08:20.147+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venvfmrxhnl8/bin/pip install -r /tmp/venvfmrxhnl8/requirements.txt
[2024-10-11T22:08:20.148+0000] {process_utils.py:187} INFO - Output:
[2024-10-11T22:08:23.452+0000] {process_utils.py:191} INFO - 
[2024-10-11T22:08:23.458+0000] {process_utils.py:191} INFO - [notice] A new release of pip is available: 24.0 -> 24.2
[2024-10-11T22:08:23.460+0000] {process_utils.py:191} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-10-11T22:08:23.579+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venvfmrxhnl8/bin/python /tmp/venv-calle9_b8b1l/script.py /tmp/venv-calle9_b8b1l/script.in /tmp/venv-calle9_b8b1l/script.out /tmp/venv-calle9_b8b1l/string_args.txt /tmp/venv-calle9_b8b1l/termination.log
[2024-10-11T22:08:23.582+0000] {process_utils.py:187} INFO - Output:
[2024-10-11T22:08:25.318+0000] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-10-11T22:08:25.323+0000] {process_utils.py:191} INFO -   File "/tmp/venv-calle9_b8b1l/script.py", line 105, in <module>
[2024-10-11T22:08:25.325+0000] {process_utils.py:191} INFO -     res = train_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-10-11T22:08:25.326+0000] {process_utils.py:191} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-11T22:08:25.326+0000] {process_utils.py:191} INFO -   File "/tmp/venv-calle9_b8b1l/script.py", line 17, in train_model
[2024-10-11T22:08:25.327+0000] {process_utils.py:191} INFO -     from sklearn.model_selection import train_test_split
[2024-10-11T22:08:25.328+0000] {process_utils.py:191} INFO - ModuleNotFoundError: No module named 'sklearn'
[2024-10-11T22:08:25.551+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-11T22:08:25.615+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
No module named 'sklearn'
[2024-10-11T22:08:25.624+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=train_ml_model_dag, task_id=train_model, run_id=manual__2024-10-11T22:08:17.954348+00:00, execution_date=20241011T220817, start_date=20241011T220819, end_date=20241011T220825
[2024-10-11T22:08:25.636+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task train_model (Process returned non-zero exit status 1.
No module named 'sklearn'; 204)
[2024-10-11T22:08:25.692+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-11T22:08:25.712+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-11T22:08:25.714+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
