[2024-10-11T22:13:27.045+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-11T22:13:27.063+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_ml_model_dag.train_model manual__2024-10-11T22:08:17.954348+00:00 [queued]>
[2024-10-11T22:13:27.067+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_ml_model_dag.train_model manual__2024-10-11T22:08:17.954348+00:00 [queued]>
[2024-10-11T22:13:27.067+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-10-11T22:13:27.074+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_model> on 2024-10-11 22:08:17.954348+00:00
[2024-10-11T22:13:27.079+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=301) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-11T22:13:27.082+0000] {standard_task_runner.py:63} INFO - Started process 303 to run task
[2024-10-11T22:13:27.082+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'train_ml_model_dag', 'train_model', 'manual__2024-10-11T22:08:17.954348+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/train_ml_model.py', '--cfg-path', '/tmp/tmpqv04zkh0']
[2024-10-11T22:13:27.085+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask train_model
[2024-10-11T22:13:27.129+0000] {task_command.py:426} INFO - Running <TaskInstance: train_ml_model_dag.train_model manual__2024-10-11T22:08:17.954348+00:00 [running]> on host 8a428b66f6b4
[2024-10-11T22:13:27.185+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Michael Mora' AIRFLOW_CTX_DAG_ID='train_ml_model_dag' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-11T22:08:17.954348+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-11T22:08:17.954348+00:00'
[2024-10-11T22:13:27.187+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-11T22:13:27.189+0000] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvw0pefcpz --system-site-packages --python=python
[2024-10-11T22:13:27.190+0000] {process_utils.py:187} INFO - Output:
[2024-10-11T22:13:27.736+0000] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 217ms
[2024-10-11T22:13:27.742+0000] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venvw0pefcpz, clear=False, no_vcs_ignore=False, global=True)
[2024-10-11T22:13:27.747+0000] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-10-11T22:13:27.748+0000] {process_utils.py:191} INFO -     added seed packages: pip==24.0
[2024-10-11T22:13:27.749+0000] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-10-11T22:13:27.761+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venvw0pefcpz/bin/pip install -r /tmp/venvw0pefcpz/requirements.txt
[2024-10-11T22:13:27.763+0000] {process_utils.py:187} INFO - Output:
[2024-10-11T22:13:31.157+0000] {process_utils.py:191} INFO - 
[2024-10-11T22:13:31.158+0000] {process_utils.py:191} INFO - [notice] A new release of pip is available: 24.0 -> 24.2
[2024-10-11T22:13:31.159+0000] {process_utils.py:191} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-10-11T22:13:31.217+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venvw0pefcpz/bin/python /tmp/venv-calloimyuu3k/script.py /tmp/venv-calloimyuu3k/script.in /tmp/venv-calloimyuu3k/script.out /tmp/venv-calloimyuu3k/string_args.txt /tmp/venv-calloimyuu3k/termination.log
[2024-10-11T22:13:31.218+0000] {process_utils.py:187} INFO - Output:
[2024-10-11T22:13:32.595+0000] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-10-11T22:13:32.598+0000] {process_utils.py:191} INFO -   File "/tmp/venv-calloimyuu3k/script.py", line 105, in <module>
[2024-10-11T22:13:32.599+0000] {process_utils.py:191} INFO -     res = train_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-10-11T22:13:32.600+0000] {process_utils.py:191} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-11T22:13:32.601+0000] {process_utils.py:191} INFO -   File "/tmp/venv-calloimyuu3k/script.py", line 17, in train_model
[2024-10-11T22:13:32.602+0000] {process_utils.py:191} INFO -     from sklearn.model_selection import train_test_split
[2024-10-11T22:13:32.602+0000] {process_utils.py:191} INFO - ModuleNotFoundError: No module named 'sklearn'
[2024-10-11T22:13:32.833+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-11T22:13:32.849+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
No module named 'sklearn'
[2024-10-11T22:13:32.857+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=train_ml_model_dag, task_id=train_model, run_id=manual__2024-10-11T22:08:17.954348+00:00, execution_date=20241011T220817, start_date=20241011T221327, end_date=20241011T221332
[2024-10-11T22:13:32.867+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task train_model (Process returned non-zero exit status 1.
No module named 'sklearn'; 303)
[2024-10-11T22:13:32.908+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-11T22:13:32.928+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-11T22:13:32.930+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
